### ISSUE TITLE
Invalid suggested_unit_of_measurement warning

### ISSUE THREAD

**Issue by MilanPala** [schizza/SWS-12500-custom-component#2]
Hi, thanks for addon. I see some warning in log:

`<class 'custom_components.sws12500.sensor.WeatherSensor'> sets an invalid suggested_unit_of_measurement. This warning will become an error in Home Assistant Core 2024.5.`

![image](https://github.com/schizza/SWS-12500-custom-component/assets/1717814/8c16fb49-8356-42a4-b489-c9b7b127c1f9)

**Comment by schizza** [comment]
Hi there, will look at it? Do you see which sensor passes this warning?

**Comment by schizza** [comment]
Fixed #5
