### ISSUE TITLE
I have firmware v 2.04, but still can't see any incoming data / entries

### ISSUE THREAD

**Issue by soadzoor** [schizza/SWS-12500-custom-component#26]
Do you have any suggestions?

<img width="1229" alt="Screenshot 2024-06-10 at 10 52 10" src="https://github.com/schizza/SWS-12500-custom-component/assets/10392261/ff2a6a03-b5e0-4ac6-9d4b-af56b650bfe1">

**Comment by schizza** [comment]
> Do you have any suggestions?
> 
> <img alt="Screenshot 2024-06-10 at 10 52 10" width="1229" src="https://private-user-images.githubusercontent.com/10392261/338116043-ff2a6a03-b5e0-4ac6-9d4b-af56b650bfe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTE4OTksIm5iZiI6MTcxODAxMTU5OSwicGF0aCI6Ii8xMDM5MjI2MS8zMzgxMTYwNDMtZmYyYTZhMDMtYjVlMC00YWM2LTlkNGItYWY1NmI2NTBiZmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA5MjYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ODI0ZDIyOGRmMzEzMjcxMTBiYTJiZWYzN2JlNTdiMDQ0NDgwYmJmODk4MDZkYmMxYTg3YTE3YTJmYWI1NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CshBxkkVWa71JHMvdDWAIBm9K38GzqWLNhJvw9aXxtg">

@soadzoor Chce that you have properly configured the station - if it is connected to AP (wifi icon should not be blinking). If it is connected, chcek IP address of HA configured in the station. If you don't have your DNS setup fill in IP address not domain (192.168.1.2:8123. not homeassistant.local:8123)

**Comment by soadzoor** [comment]
Awesome, thank you! Changing `homeassistant.local:8123` to `<ipaddress of HA>:8123` did the trick! After a reboot of the HA server, I already started receiving the actual data as well!

![image](https://github.com/schizza/SWS-12500-custom-component/assets/10392261/1199ddab-e210-4e77-ad85-a040bc9d6882)
