### ISSUE TITLE
Support for 2nd channel will be added in next release.

### ISSUE THREAD

**Issue by schizza** [schizza/SWS-12500-custom-component#4]
In next release there will be automatic discovery for second temperature sensor as soon as the weather station will start sending data.

**Comment by soadzoor** [comment]
@schizza 
Hello,

First of all thank you for this awesome integration, it's super stable, and works very nicely, and reliably!

I have a question though: I added an additional external sensor for channel 7 now, but I'm not sure what I should do in order to make it appear on the entities. I already tried reloading the integration, it didn't help.

Could you please point me to the right direction?

Thank you!

<img width="645" height="1398" alt="Image" src="https://github.com/user-attachments/assets/3ec3b1dc-e51b-4f56-bcb0-8d70f092e1da" />

**Comment by schizza** [comment]
> [@schizza](https://github.com/schizza) Hello,
> 
> First of all thank you for this awesome integration, it's super stable, and works very nicely, and reliably!
> 
> I have a question though: I added an additional external sensor for channel 7 now, but I'm not sure what I should do in order to make it appear on the entities. I already tried reloading the integration, it didn't help.
> 
> Could you please point me to the right direction?
> 
> Thank you!
> 
> <img alt="Image" width="645" height="1398" src="https://private-user-images.githubusercontent.com/10392261/547063325-3ec3b1dc-e51b-4f56-bcb0-8d70f092e1da.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA5MDIwODAsIm5iZiI6MTc3MDkwMTc4MCwicGF0aCI6Ii8xMDM5MjI2MS81NDcwNjMzMjUtM2VjM2IxZGMtZTUxYi00ZjU2LWJjYjAtOGQ3MGYwOTJlMWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjEyVDEzMDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNjBlYzVlODU5Yzc4ZGRiYTE1MWVjNjRhYjYyOTQyMzQ1MTNkMjhhOTIxMDZjMzYxNzEyYWRjNzhiMjhlZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OI-tFJgjP3jWOhSs_5nSW9MpGd_WE56-UnP6xy2I4pg">

Hi there, 
It depend on which protocol you use, if PWS, then 7th sensor is not sending by the station. If PWS, sensor will be added in next release.
You can enable debug log and debugging of integration in HA a send the log to me - if station is sending additional data.

**Comment by soadzoor** [comment]
@schizza sorry, I'm really confused.

I don't know what protocols there are, I added your integration about 2 years ago, and followed the instructions in your README file. Now I can see it mentions some kind of a WSLink protocol, but I don't remember switching to that.

You also mention in your comment:

"If PWS, then sensor is not sending by the station", then
"If PWS, sensor will be added in the next release".

I guess one of those "PWS" should be "WSLink"...? Which one? Should I upgrade to WSLink, or should I leave it as it is (probably PWS, although not 100% sure)...?

When is the next release expected to be available?

**Comment by schizza** [comment]
Sorry, PWS does not support more sensors. WSLink does support more sensors. 
I have almost done refactoring whole integration. 
I don't think that "upgrade" to WSLink is passible with older stations. I know only new SWS12500 are shipped with FW3.0, that supports WSLink.
